### ISSUE TITLE
Firefox HTTPS only mode on HTTP dev site

### ISSUE THREAD

**Issue by ssnepenthe** [underground-works/clockwork-app#108]
So... I am not sure if this is intended behavior or not and I am not sure if this report belongs here or if it is an issue with Firefox itself.

I have recently been using HTTPS only mode in Firefox - https://support.mozilla.org/en-US/kb/https-only-prefs.

For local development I might edit my hosts file to make my site accessible via a domain like `laravel.test`.

Because the site is HTTP only I will then add an exception to the HTTPS only settings to disable for `http://laravel.test` in order to visit the site.

So far, this is all as expected.

However... Even with that exception in place, the Clockwork browser extension is no longer able to access the Clockwork API.

Any insight on why this might be or advice on how to debug?

**Comment by itsgoingd** [comment]
Hey, seems like a Firefox issue or limitation of the https-only mode.

I've found a workaround that seems to make it work - adding the extension page itself to the exceptions. To do this you will first have to find out the extension page url, you can do so by going to `about:debugging`, This Firefox, and clicking on the Clockwork extension.

Here you will find the "Manifest URL", copy the url, without the manifest.json at the end, into the https-only exceptions. Let me know if this works for you.

**Comment by ssnepenthe** [comment]
Yes that worked, thanks for the quick response!
