### ISSUE TITLE
Performance profiler loading "Processing profile..." forever

### ISSUE THREAD

**Issue by natenatters** [underground-works/clockwork-app#109]
Using a fresh Laravel install `curl -s "https://laravel.build/example-app" | bash` and ran `./vendor/bin/sail artisan migrate`.

Added these to my .env:
```
SAIL_XDEBUG_MODE=profile
SAIL_XDEBUG_CONFIG="client_host=host.docker.internal output_dir=/var/www/html/storage/app"
```

Then `./vendor/bin/sail composer require itsgoingd/clockwork`.
Then `./vendor/bin/sail up`.

When I have `http://localhost/clockwork/app` open in Chrome, then make a request to `http://localhost` in another Chrome tab, the request appears in the Clockwork app! But, if I click "Profiler", it is stuck on "Processing profile..." forever.

I also get a JS bug in Chrome dev tools, I tracked it down to this line:
https://github.com/underground-works/clockwork-app/blob/master/src/features/callgrind/callgrind.js#L62

The line is a string of value `"0"`, but other times its undefined... So it cant split it by ' '.

Do you know if this is valid? Or if its something wrong with my Xdebug setup/ profiling?

My uneducated guess is that the cachegrind.out.%p files are still being written too when Clockwork requests them, so its only reading half or none of a line. I only think this because I opened one of them and it was always being updated. BUT, could be a red herring.

Thanks for any help. Clockwork is and has always been a great addition to my tools :D

**Comment by natenatters** [comment]
Updates:

I can read the cachegrind.out.%p files in Webgrind by running:
`docker run --rm -v /{path-ro-repo}/storage/app:/tmp -p 80:80 jokkedk/webgrind:latest`
This leads me to believe the profiler output is good.

I noticed this: https://github.com/itsgoingd/clockwork/issues/569

So I tried it with Xdebug config for `use_compression=false`, but the problem persists.

**Comment by natenatters** [comment]
Resolved. It was an issue with my naming convention for the filename.
I changed my .env:
```
SAIL_XDEBUG_MODE=profile
SAIL_XDEBUG_CONFIG="client_host=host.docker.internal output_dir=/var/www/html/storage/app profiler_output_name=cachegrind.out.%R use_compression=false"
```
This is after advice from Dericks video here: https://www.youtube.com/watch?v=ttQgLBSpVvc

**Comment by itsgoingd** [comment]
Hey, have you figured out why do you need to change the profile file name? The default filename uses PID as part of the name, I wonder if the processes get reused under php-fpm and different requests end up writing to the same file effectively corrupting the profile. 🤔

**Comment by natenatters** [comment]
Good guess. I only had 2 profiler outputs, here are the headers:

cachegrind.out.15
```
version: 1
creator: xdebug 3.1.5 (PHP 8.1.10)
cmd: /var/www/html/artisan
part: 1
positions: line
```

cachegrind.out.16
```
version: 1
creator: xdebug 3.1.5 (PHP 8.1.10)
cmd: /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php
part: 1
positions: line
```

So I think all the HTTP requests were appended to that cachegrind.out.16 file. If you watch the YouTube video at 1:15 (https://youtu.be/ttQgLBSpVvc?t=74), he says the default profiler_output_name isnt very useful 😆  and recomends the %R (See allowed specifiers here: https://xdebug.org/docs/all_settings#trace_output_name).

**Comment by natenatters** [comment]
Sorry if I am posting too much, I am now learning more about Xdebug 😄  In another [video](https://youtu.be/iH-hDOuQfcY?t=60), he uses the timestamp in the filename too:
```
output_dir=/tmp/profiles
profiler_output_name=cachegrind.out.%R.%u
```

**Comment by itsgoingd** [comment]
No, I appreciate the info. I wonder why keep the default tho if it's the case it doesn't work well with php-fpm, which is by far the most used way to run php nowdays.

Personally I would probably use the pid (%p) in combination with timestamp (%u) or random number (%r), but Clockwork shouldn't care.

It might be a good idea to bring this up with Xdebug devs and suggest better defaults here. I will also update Clockwork docs to mention changing this setting.

**Comment by natenatters** [comment]
I used [WebGrind](https://github.com/jokkedk/webgrind) to read the default filename and it worked fine, so it makes me think its something with Clockwork parsing the file wrong. But not a huge issue.

Perhaps the default file is to make it easier to cleanup, as it could endup filling your tmp directory.
