### ISSUE TITLE
npm run build-chrome can't copy directory

### ISSUE THREAD

**Issue by fedorovsergey** [underground-works/clockwork-app#115]
Hello! 
Hello! I have been tried to install app from source on Windows 10, npm v9.7.2, node v16.14.2.
Git clone
npm install
npm run build-chrome
vue project build completed, but other commands not work properly and show an error
`
.......
✓ 722 modules transformed.
dist/index.html                  0.41 KiB
dist/assets/index.2d12963a.css   75.52 KiB / gzip: 11.08 KiB
dist/assets/index.48614b73.js    475.75 KiB / gzip: 151.57 KiB
[Error: ENOENT: no such file or directory, rename 'PATH\clockwork-app\build' -> 'PATH\clockwork-app\dist\chrome'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'PATH\\clockwork-app\\build',
  dest: 'PATH\\clockwork-app\\dist\\chrome'
}
`
(I replaced my actual project path with "PATH" word)
I can't find any mention about 'build' directory or way, how it may be created. 
What am I doing wrong?

**Comment by itsgoingd** [comment]
Hey, fixed this in master, we've recently switched to Vite as our build system and it uses a different default build dir.
