### ISSUE TITLE
How to enable hot reload?

### ISSUE THREAD

**Issue by fedorovsergey** [underground-works/clockwork-app#116]
Hello! 
Is there a way to not npm build -> browser://extensions/ -> reload -> F12 close-open on every change?
May be you use some kind of automatization?
It would be great if you give me a piece of advice! Thanks)

**Comment by itsgoingd** [comment]
Hey, unfortunately I don't know about a way to make hot-reload work with extensions. I usually develop Clockwork as a standalone web app using `npm run serve` and test a browser build every now and then.

**Comment by fedorovsergey** [comment]
Thank you for you answer! 
When I start it in your way, I get an error, "Access to fetch at 'https://myhost.org/...../latest' from origin 'http://127.0.0.1:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request."
My site is closed by authorization. Anyway I have to add Access-Control headers from server side, right?

**Comment by itsgoingd** [comment]
Yeah, your backend will need to send an appropriate Access-Control headers to allow ajax requests from localhost.
