### ISSUE TITLE
Query duration is being sorted like a string

### ISSUE THREAD

**Issue by fitztrev** [underground-works/clockwork-app#13]
Chrome extension version: 4.0.1
PHP package version: 4.0.4

<img width="115" alt="clockwork-sort" src="https://user-images.githubusercontent.com/271432/61329038-5b739c80-a7ea-11e9-86a1-ddca53ee5849.png">

In screenshot above, Duration is sorted descending. `33.74` and `32.12` should be at the top.

**Comment by itsgoingd** [comment]
Fixed in 4.0.2, thanks for the report!

**Comment by fitztrev** [comment]
@itsgoingd thanks!
