### ISSUE TITLE
N+1 Queries are not showing anywhere

### ISSUE THREAD

**Issue by Vai2kas** [underground-works/clockwork-app#16]
Hello,
N+1 Queries are not showing anywhere, just shows a warning icon next to a request.

Came up with setting slow query threshold to 1 or 0, and N+1 queries now shows up.
Changing threshold to something higher, N+1 queries shows less queries (maybe it depends on threshold, not sure...)

**Comment by itsgoingd** [comment]
Hey, there was a bug where performance warning were shown only for requests with slow queries. This is now fixed, your extension should auto-update.

**Comment by Vai2kas** [comment]
It's working now. Thank you!
