### ISSUE TITLE
Request selection jumps to first

### ISSUE THREAD

**Issue by Vai2kas** [underground-works/clockwork-app#21]
Hello, 
request selection jumps back to first request in a list after new request appears. It's almost impossible to debug something.

**Comment by itsgoingd** [comment]
Hey, is this the latest Chrome version or running in standalone mode? Any more detailed steps to reproduce this behavior or it just always happens? Do you happen to have "preserve log" disabled? Could you possibly make a short recording demonstrating the bug?

**Comment by Vai2kas** [comment]
Hi, I'm using the latest Chrome version. Yes, it happens only, when "Preserve log" is disabled. Is it intended to that? I thought this setting works only on full page reload.

**Comment by itsgoingd** [comment]
Pushed a new version 4.0.7 with a fix, your extension should update automatically. Let me know if it works for you.

**Comment by Vai2kas** [comment]
Thank you! Request selection doesn't jump anymore.
