### ISSUE TITLE
Broken Array with key ''

### ISSUE THREAD

**Issue by mahagr** [underground-works/clockwork-app#29]
If you have an array with empty key such as

```
{'':'foo'}
```

It appears as an infinitely recursive array.

**Comment by itsgoingd** [comment]
Any specific steps to reproduce the behavior?

Tried reproducing with `clock([ '' => 'foo' ])`, but that seems to work fine.

**Comment by mahagr** [comment]
I've not forgotten this, just been super busy. I'll try to get into this asap.

**Comment by mahagr** [comment]
Fixed in here: https://github.com/getgrav/grav/commit/0bbbe96ae0d577bc55e4c5f29cb7ba5348c573e2

**Comment by mahagr** [comment]
Ok, working example, try adding this debug message from PHP: `['' => new \stdClass()]`

**Comment by itsgoingd** [comment]
Fixed in master (https://github.com/underground-works/clockwork-app/commit/a371c5311a42f09e8f864d671b4521e71baab9a9), thanks!

**Comment by mahagr** [comment]
Thank you!
