### ISSUE TITLE
Improve presentation of website with BeerSlider JS plugin

### ISSUE THREAD

**Issue by llaville** [underground-works/clockwork-app#33]
Hello,

While I looked at [RapiDoc](https://mrin9.github.io/RapiDoc/) site (that i follow), i discover a real JS cool plugin => the BeerSlider, that allow to look the light and dark theme look like dynamically.
More than a long talk, have a look on site https://pepsized.com/wp-content/uploads/2018/09/beerslider/demo/index.html there are some demos online.

Just an improvement idea !

**Comment by itsgoingd** [comment]
Will keep in mind when I'm redesigning the website next, thanks.
