### ISSUE TITLE
Error loading request metadata

### ISSUE THREAD

**Issue by piranha** [underground-works/clockwork-app#35]
Hey! If you remember, about a year ago I wrote [clojure version](https://github.com/kasta-ua/clj-clockwork) of server library. Today I noticed that on our bigger pages (in terms of debug payload, so many queries to db, a lot of stacktraces, etc) instead of showing details of request, we this error.

Unfortunately, debugging vue.js app seems to be even harder than debugging angular version and I can't really understand what causes this. Maybe you've changed some format in process of releasing 4.0? On pages with less info everything works. :)

If you need, I can post my full server response, but in case it helps, here is keys of JSON I return from server:

```
> curl -s http://dev.mk:5000/__clockwork/2f874ae6-13f3-4bd3-8715-b186e8a6e58f | jq -c 'keys'
["cacheTime","controller","cookies","databaseDuration","databaseQueries","getData","headers","id","log","memoryUsage","postData","responseDuration","responseStatus","responseTime","time","timelineData","uri","url","version"]
```

**Comment by itsgoingd** [comment]
Hey, I'm trying to keep the app compatible with all previous metadata versions, but it's possible I broke something unintentionally.

A full server response would be very helpful, you can send it via email at `info@underground.works` if you don't want to post it publicly.

Btw. I'm very interested in any feedback you might have from building the clojure library. I was thinking about writing some non-php implementation myself to demonstrate how the app can be used as an universal debugging tool.

**Comment by piranha** [comment]
Well... I should have written that a year ago, when I was researching that stuff. :-) Basically we've been using miniprofiler for a long time, but it was a little bit irritating in an SPA setup, since list of requests just grows infinitely. 

So I set out, researched data types (even had partial schema for that, but later dropped since it was clear enough) and wrote a Clojure implementation of server. It doesn't do everything PHP does (and I remember being jealous of something - I will look into this again when we fix my stuff :)), but it does quite a bit! Logs, timings (like for db query, etc). It's nice!

It would be great to write a doc on data types to return from API and then promote Clockwork as a cross-platform lightweight profiler. :-)

I'll send my API response to your email in a bit.

**Comment by itsgoingd** [comment]
Took a look at your data, there is a single database query where you are logging an array of results or bindings instead of the sql under the `query` key (look for a query with "fdb get" as `model`). 

We expect the query to always be a string, after removing that one object the requests loads fine. Btw. in Clockwork 4.1 you will be able to collect query bindings under a `bindings` key.

Good point with the metadata specification, this is definitively on the todo list. I've actually written one way back for 1.x, but never published it because I didn't want to commit to a particular format. I'm actually considering major changes to the format for the first time in the next major release, but the app will always be compatible with all past metadata versions.

Always cool to see people using Clockwork in an unintended or innovative ways. :)

**Comment by piranha** [comment]
Damn! How'd you found it?

> Always cool to see people using Clockwork in an unintended or innovative ways. :)

Well, I don't even know... it seems to me it's exactly the intended way. :-))

**Comment by piranha** [comment]
You know what would be lovely? A way to embed a link or something like that.

I have a way to profile my app and get an SVG flamegraph out of it, but it takes looking at the code to even remember how to do that. Would be nice to have a link to flamegraph somewhere in Clockwork interface. :-)

**Comment by itsgoingd** [comment]
Vue does some funky error handling that eats up some exceptions. You have to turn on "pause on caught exceptions" in dev tools to find out that the metadata parsing code actually throws an exception.

I guess we could make links in log messages clickable? Btw. you can also make a log message appear in the "performance" tab by using `{ performance: true }` as its context.
