### ISSUE TITLE
Be able to tweak interval of updates

### ISSUE THREAD

**Issue by raulferras** [underground-works/clockwork-app#40]
If I'm not doing anything extremely wrong, I've seen that the browser extension is querying my server too frequently to my taste. I would like to be able to reduce the interval this requests are triggered. I guess this is to cover Single Page Applications.

My current setup includes Docker and each request takes a considerable time to process. One or two does no harm, but running requests continuously impacts severely the performance of my computer. Also I'm not developing an SPA so I could happily disable this feature.

Is there a way to increase the time between requests?

**Comment by itsgoingd** [comment]
hey, the clockwork 4.1 extension works in two modes:

- polling - if you are collecting commands, jobs or tests
- on-demand - if you are collecting only http requests

to use the way less network-heavy "on-demand" mode you have to have all the "hide commands/jobs/tests" settings enabled in the extension (this should be the default).

for the web ui (your.app/__clockwork) we always have to do polling, but we automatically throttle the polling interval to one minute if the browser tab is not active.

there is definitively a room for improvement here:

- explore whether we can use the same throttling mechanism when polling in extension
- dynamic polling interval based on server response time
