### ISSUE TITLE
Timeline: Threshold filter

### ISSUE THREAD

**Issue by gharlan** [underground-works/clockwork-app#46]
It would be great to have a threshold filter like in symfony profiler:

![Screenshot 2020-06-22 10 47 39](https://user-images.githubusercontent.com/330436/85268350-af651780-b476-11ea-919a-8398839c7988.png)

**Comment by itsgoingd** [comment]
agreed, some timeline improvements are already planned for the next release, adding this one to the list as well

**Comment by itsgoingd** [comment]
i just remembered this is already kinda possible with search. you can search for `duration:>2` to show only events taking more than 2 ms (similar search queries work for stuff like database queries etc).

(still working on a much better overall timeline experience, will be publishing PR soon)
