### ISSUE TITLE
standalone: add way to define subpath for remote url

### ISSUE THREAD

**Issue by edgardmessias** [underground-works/clockwork-app#61]
Currently I work with a project using subpath, but with the new version (v5.0.0-beta0) is not possible to use standalone app, because all urls are redirect to root (/__clockwork/latest instead of /my_sub_path/__clockwork/latest)

A possible alternative for: https://github.com/underground-works/clockwork-app/blob/94e07791c18975d72412805e765137274b96178f/src/platform/standalone.js#L37

```js
// From
this.requests.setRemote(
    window.location.href, { path: '__clockwork/' }
)

// To
this.requests.setRemote(
    window.location.href,
    { path: window.CLOCKWORK_BASE_PATH || '__clockwork/' }
)
```

After that, edit the '[getWebAsset](https://github.com/itsgoingd/clockwork/blob/ed7407be8d4cfee2210e0285e21f7e6769db024d/Clockwork/Support/Laravel/ClockworkSupport.php#L155)' to prepend the global variable

**Comment by itsgoingd** [comment]
I see, we used to auto-detect the api path form the current URI, but this is no longer possible since Clockwork 5 has configurable web ui path. Will have to come up with something better.

Thanks for testing the beta, very useful feedback. :)

**Comment by itsgoingd** [comment]
Re-added api endpoint detection in 5.0-beta1. Can you give it a try?

**Comment by edgardmessias** [comment]
@itsgoingd its work now.

And, what you think about meta tags?

Example:
```html
<meta name="clockwork-remote-url" content="<full url or path only>">
```
```js
const remoteUrl = document.querySelector('meta[name="clockwork-remote-url"]')?.content;
```

**Comment by itsgoingd** [comment]
I'm not sure what the use case would be, is there a case where the current auto-detection is not good enough?
