### ISSUE TITLE
No code editor listed in settings

### ISSUE THREAD

**Issue by shaffe-fr** [underground-works/clockwork-app#73]
Hi,

Firefox version: 85.0b9 developer edition
Clockwork extension version: 5.0.2

In firefox clockwork extension settings, no code editors are listed:
![image](https://user-images.githubusercontent.com/3834222/105378712-5fb51d00-5c0c-11eb-818d-954319a0e90f.png)

When I click on the Code editor dropdown, the following errors appears in the browser console:
>TypeError: can't access property "getFullZoomForBrowser", ZoomManager is undefinedSelectParent.jsm:745:1
    receiveMessage resource://gre/actors/SelectParent.jsm:745

```js
SelectParentHelper.populate(
    menulist,
    data.options.options,
    data.options.uniqueStyles,
    data.selectedIndex,
    // We only want to apply the full zoom. The text zoom is already
    // applied in the font-size.
    ZoomManager.getFullZoomForBrowser(browser), // ERROR IS HERE
    data.defaultStyle,
    data.style
);
```

Thanks

**Comment by itsgoingd** [comment]
Hey, this looks like a Firefox bug. It seems to work again in the latest developer edition, although the styles for the input are still a bit broken.
